name: "cargo-machete"
description: "A github action for cargo machete"
author: "Cargo machete community"
branding:
  color: "black"
  icon: "code"
runs:
  using: composite
  steps:
    - name: Install cargo-machete
      run: cargo install cargo-machete
      shell: bash

    - name: Machete
      run: cargo machete
      shell: bash
